<template>
  <section>
    <el-row>
      <a href="/" class="title">USSLAB Recommend Conference Deadlines</a>
    </el-row>
    <el-row class="subtitle">
      The conference deadlines are recommended by <a href="http://usslab.org/">USSLAB(Ubiquitous System Security Lab)</a>.
    </el-row>
    <el-row class="subtitle">
      To add/edit a conference, please create <a href="https://github.com/ZJUshine/usslab-conference-ddls/issues">issues</a>.
    </el-row>
    <el-row class="subtitle">
      Generated by <a style="color: #666666" href="https://github.com/ZJUshine/usslab-deadlines">https://github.com/ZJUshine/usslab-deadlines</a>.
    </el-row>
    <el-row class="subtitle">
      The author of this website is <a style="color: #666666" href="https://zjushine.github.io/">ZJUshine</a>.
    </el-row>
  </section>
</template>

<style scoped>
.title{
  font-size: 29px;
  color: #2c3e50;
}
.subtitle{
  padding-top: 15px;
  color: #666666;
}
</style>
